FROM node:20-slim AS base

WORKDIR /app

COPY mcp-server/package.json ./package.json
COPY mcp-server/tsconfig.json ./tsconfig.json
COPY mcp-server/src ./src

RUN npm install && npm run build && npm prune --production

EXPOSE 8000

CMD ["node", "dist/index.js"]

